Update test_ci.yml

diff --git a/.github/workflows/test_ci.yml b/.github/workflows/test_ci.yml
--- a/.github/workflows/test_ci.yml
+++ b/.github/workflows/test_ci.yml
@@ -1,30 +1,34 @@
-name: CI
+name: CI Pipeline
 
-on:
-  push:
-    branches:
-      - main
+on: [push, pull_request]
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+    - uses: actions/checkout@v2
 
-    - name: Set up Python 3.12
-      uses: actions/setup-python@v4
+    - name: Set up Python
+      uses: actions/setup-python@v2
       with:
-        python-version: 3.12
+        python-version: '3.12.4'
+
+    - name: Check for requirements.txt
+      run: |
+        if [ ! -f requirements.txt ]; then
+          echo "requirements.txt not found"
+          exit 1
+        fi
 
     - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r project/requirements.txt
+      run: pip install -r requirements.txt
+
+    - name: Make scripts executable
+      run: chmod +x pipeline.sh tests.sh
+
+    - name: Run pipeline
+      run: bash pipeline.sh
 
     - name: Run tests
-      run: |
-        python -m unittest discover -s . -p 'tests.py'
-          chmod +x tests.sh
-            ./tests.sh
+      run: bash tests.sh
